baseURL = 'https://cv.korsak.xyz/'
languageCode = 'en-us'
title = 'Jakub Korsak CV'
theme = 'cv-jk'
relativeURLS = true

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
